add the player-api executable to the archive

diff --git a/build b/build
--- a/build
+++ b/build
@@ -17,5 +17,27 @@ find . -name "version.go" | while read versionfile; do
     sed -i "s@<GIT_URL>@${GIT_URL}@g"       ${versionfile}
 done
 
+mkdir -p ${WORKSPACE}/bin
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+echo '{}' | jq --arg foo "${BUILD_ID}"   '. + {version: $foo}'   > temp1
+cat temp1 | jq --arg foo "${BUILD_DATE}" '. + {buildDate: $foo}' > temp2
+cat temp2 | jq --arg foo "${GIT_COMMIT}" '. + {gitCommit: $foo}' > temp3
+cat temp3 | jq --arg foo "${GIT_BRANCH}" '. + {gitBranch: $foo}' > temp4
+cat temp4 | jq --arg foo "${GIT_URL}"    '. + {gitURL: $foo}'    > ${WORKSPACE}/bin/version.json
+
+rm -rf temp*
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
 go get -d ./...
 go install ./...
