add scripts for players-api scripts

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -33,9 +33,17 @@ if [ ! ${result} == 0 ]; then
     exit 1
 fi
 #****************************************************************
-#* Deploy the main executable
+#* Deploy the main executable and test utilities 
 #****************************************************************
 zip ${FILENAME} players-api version.json
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+zip ${FILENAME_TEST} generate-test-data
 result=$?
 if [ ! ${result} == 0 ]; then
     echo "Error: $0[${LINENO}]"
