add the player-api executable to the archive

diff --git a/post-build b/post-build
--- a/post-build
+++ b/post-build
@@ -16,18 +16,37 @@ FILENAME=${JOB_NAME}-${GOARCH}-${GOOS}-${BUILD_ID}.${PACKAGING}
 
 BUILD_DATE=$(date "+%Y/%m/%d %H:%M:%S")
 
-echo '{}'   | jq --arg foo "${BUILD_ID}"   '. + {version: $foo}' > f1.json
-cat f1.json | jq --arg foo "${BUILD_DATE}" '. + {buildDate: $foo}' > f2.json
-cat f2.json | jq --arg foo "${GIT_COMMIT}" '. + {gitCommit: $foo}' > f3.json
-cat f3.json | jq --arg foo "${GIT_BRANCH}" '. + {gitBranch: $foo}' > f4.json
-cat f4.json | jq --arg foo "${GIT_URL}"    '. + {gitURL: $foo}' > version.json
+currentDir=$(pwd)
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
 
-pwd
-ls -al
-cat version.json
-jq . version.json
+cd ${WORKSPACE}/bin
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
 
-zip ${FILENAME} ${WORKSPACE}/bin/players-api version.json
+rm -rf ${FILENAME} temp*.json version.json
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
+
+echo '{}' | jq --arg foo "${BUILD_ID}"   '. + {version: $foo}'   > temp1
+cat temp1 | jq --arg foo "${BUILD_DATE}" '. + {buildDate: $foo}' > temp2
+cat temp2 | jq --arg foo "${GIT_COMMIT}" '. + {gitCommit: $foo}' > temp3
+cat temp3 | jq --arg foo "${GIT_BRANCH}" '. + {gitBranch: $foo}' > temp4
+cat temp4 | jq --arg foo "${GIT_URL}"    '. + {gitURL: $foo}'    > version.json
+
+zip ${FILENAME} players-api version.json
 result=$?
 if [ ! ${result} == 0 ]; then
     echo "Error: $0[${LINENO}]"
@@ -56,3 +75,10 @@ if [ ! ${result} == 0 ]; then
     exit 1
 fi
 
+cd ${currentDir}
+result=$?
+if [ ! ${result} == 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    exit 1
+fi
