new version

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -34,17 +34,16 @@ fi
 echo "------------------------------------------------------------------"
 echo "Register"
 
-COMMAND="/users/register"
+COMMAND="/register"
 
 rm -rf dump-header.txt output.json status.txt cookie-jar.txt
 
 cat <<EOF > data.json
 {
-    "registration": {
+    "register": {
         "firstname": "James",
         "lastname": "Bond",
         "displayname": "007",
-        "username": "${USERNAME}",
         "email": "${EMAIL}",
         "phone": "${PHONE}",
         "password": "${PASSWORD}"
@@ -101,17 +100,30 @@ echo "------------------------------------------------------------------"
 echo "=================================================================="
 echo "admin Authenticate"
 
-COMMAND="/users/authenticate"
+COMMAND="/signin"
 
 rm -rf dump-header.txt output.json status.txt
 
+cat <<EOF > data.json
+{
+    "signin": {
+        "username": "${PLAYERS_ADMIN_EMAIL}",
+        "password": "${PLAYERS_ADMIN_PASSWORD}"
+    }
+}
+EOF
+
+echo "data.json"
+jq . data.json
+
 set -x
-curl ${OPTIONS} -X POST -u "${PLAYERS_ADMIN_USERNAME}:${PLAYERS_ADMIN_PASSWORD}" ${ENDPOINT}${COMMAND} \
+curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
 --silent \
 --cookie cookie-jar.txt \
 --cookie-jar cookie-jar.txt \
 --header "Content-Type: application/json" \
 --header "Accept: application/json" \
+--data-binary "@data.json" \
 --dump-header dump-header.txt \
 --output output.json \
 --write-out %{http_code} > status.txt
@@ -140,37 +152,98 @@ fi
 
 
 
-word=$(grep Access-Token dump-header.txt | cut -d " " -f 2)
-AdminAccessToken=${word%%[[:space:]]}
-echo "AdminAccessToken: [${AdminAccessToken}]"
 
-AdminRefreshToken=$(grep Set-Cookie dump-header.txt | cut -d " " -f 2 | cut -d "=" -f 2)
-echo "AdminRefreshToken: [${AdminRefreshToken}]"
+echo "---[ dump-header.txt ]----------------"
+cat dump-header.txt
+echo "--------------------------------------"
+
+echo "---[ cookie-jar.txt ]----------------"
+cat cookie-jar.txt
+echo "--------------------------------------"
+
+
+
+
+AdminAccessToken=$(jq -r '.accessToken' output.json)
+echo "AdminAccessToken: ${AdminAccessToken}"
+
+
 
 adminID=$(jq -r '.person.id' output.json)
 echo "adminID: ${adminID}"
+
+echo "------------------------------------------------------------------"
+echo "admin - Refresh tokens"
+
+COMMAND="/refresh"
+
+rm -rf dump-header.txt output.json status.txt
+
+set -x
+curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
+--silent \
+--cookie cookie-jar.txt \
+--cookie-jar cookie-jar.txt \
+--header "Content-Type: application/json" \
+--header "Accept: application/json" \
+--header "Authorization: Bearer ${AdminAccessToken}" \
+--data-binary "@data.json" \
+--dump-header dump-header.txt \
+--output output.json \
+--write-out %{http_code} > status.txt
+result=$?
+set +x
+
+echo "result: ${result}"
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    exit 1
+fi
+
+if [ -f output.json ]; then
+    jq . output.json
+fi
+
+status=$(cat status.txt)
+echo "status: ${status}"
+if [ "${status}" -eq 200 ]; then
+    : # ok
+else
+    echo "Error: $0[${LINENO}]"
+    echo "status: ${status}"
+    exit 1
+fi
+
+
+
+AdminAccessToken=$(jq -r '.accessToken' output.json)
+echo "AdminAccessToken: ${AdminAccessToken}"
+
 
 
 echo "------------------------------------------------------------------"
 echo "admin - Find the ID of the new user"
 
-COMMAND="/users"
+COMMAND="/people"
 
 rm -rf dump-header.txt output.json status.txt
 
 cat <<EOF > data.json
 {
     "query": {
-        "username": {
+        "email": {
             "operation": "=",
-            "value": "${USERNAME}"
+            "value": "${EMAIL}"
         }
     }
 }
 EOF
 
+echo "data.json"
+jq . data.json
+
 set -x
-curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
+curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
 --silent \
 --cookie cookie-jar.txt \
 --cookie-jar cookie-jar.txt \
@@ -215,13 +288,10 @@ fi
 
 userID=$(jq '.people[0]' output.json)
 
-
-
-
 echo "------------------------------------------------------------------"
 echo "admin - Allow the new user to log in"
 
-COMMAND="/users/${userID}"
+COMMAND="/people/${userID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -273,7 +343,7 @@ echo "------------------------------------------------------------------"
 echo "------------------------------------------------------------------"
 echo "admin - Log out"
 
-COMMAND="/users/logout"
+COMMAND="/signout"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -313,28 +383,36 @@ fi
 
 echo "------------------------------------------------------------------"
 
-
-
-
-
-
 echo "=================================================================="
-
 
 echo "------------------------------------------------------------------"
 echo "Login as the new user"
 
-COMMAND="/users/authenticate"
+COMMAND="/signin"
 
 rm -rf dump-header.txt output.json status.txt
 
+
+cat <<EOF > data.json
+{
+    "signin": {
+        "username": "${EMAIL}",
+        "password": "${PASSWORD}"
+    }
+}
+EOF
+
+echo "data.json"
+jq . data.json
+
 set -x
-curl ${OPTIONS} -X POST -u "${USERNAME}:${PASSWORD}" ${ENDPOINT}${COMMAND} \
+curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
 --silent \
 --cookie cookie-jar.txt \
 --cookie-jar cookie-jar.txt \
 --header "Content-Type: application/json" \
 --header "Accept: application/json" \
+--data-binary "@data.json" \
 --dump-header dump-header.txt \
 --output output.json \
 --write-out %{http_code} > status.txt
@@ -361,17 +439,20 @@ else
     exit 1
 fi
 
-word=$(grep Access-Token dump-header.txt | cut -d " " -f 2)
-AccessToken=${word%%[[:space:]]}
-echo "AccessToken: [${AccessToken}]"
 
-RefreshToken=$(grep Set-Cookie dump-header.txt | cut -d " " -f 2 | cut -d "=" -f 2)
-echo "RefreshToken: [${RefreshToken}]"
+
+AccessToken=$(jq -r '.accessToken' output.json)
+echo "AccessToken: ${AdminAccessToken}"
+
+
+
+userID=$(jq -r '.person.id' output.json)
+echo "userID: ${userID}"
 
 echo "------------------------------------------------------------------"
-echo "Read the new person"
+echo "Read the new user"
 
-COMMAND="/users/${userID}"
+COMMAND="/people/${userID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -410,9 +491,9 @@ else
 fi
 
 echo "------------------------------------------------------------------"
-echo "Update the person"
+echo "Update the user"
 
-COMMAND="/users/${userID}"
+COMMAND="/people/${userID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -423,6 +504,9 @@ cat <<EOF > data.json
     }
 }
 EOF
+
+echo "data.json"
+jq . data.json
 
 set -x
 curl ${OPTIONS} -X PUT ${ENDPOINT}${COMMAND} \
@@ -466,7 +550,7 @@ fi
 echo "------------------------------------------------------------------"
 echo "Create a new court"
 
-COMMAND="/court"
+COMMAND="/courts"
 EMAIL="smcgrath@pinky.com"
 PASSWORD="changeme"
 
@@ -487,6 +571,7 @@ curl ${OPTIONS} -X POST -u "${EMAIL}:${PASSWORD}" ${ENDPOINT}${COMMAND} \
 --cookie-jar cookie-jar.txt \
 --header "Content-Type: application/json" \
 --header "Accept: application/json" \
+--header "Authorization: Bearer ${AccessToken}" \
 --data-binary "@data.json" \
 --dump-header dump-header.txt \
 --output output.json \
@@ -521,7 +606,7 @@ echo "courtID: ${courtID}"
 echo "------------------------------------------------------------------"
 echo "Update the court"
 
-COMMAND="/court/${courtID}"
+COMMAND="/courts/${courtID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -572,7 +657,7 @@ fi
 echo "------------------------------------------------------------------"
 echo "Make a player play"
 
-COMMAND="/users/toplaying/${userID}/${courtID}"
+COMMAND="/people/toplaying/${userID}/${courtID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -615,7 +700,7 @@ fi
 echo "------------------------------------------------------------------"
 echo "Make a player wait"
 
-COMMAND="/users/towaiting/${userID}"
+COMMAND="/people/towaiting/${userID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -657,7 +742,7 @@ fi
 echo "------------------------------------------------------------------"
 echo "Make a player inactive"
 
-COMMAND="/users/toinactive/${userID}"
+COMMAND="/people/toinactive/${userID}"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -741,7 +826,7 @@ fi
 echo "------------------------------------------------------------------"
 echo "List people"
 
-COMMAND="/users"
+COMMAND="/people"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -757,7 +842,7 @@ cat <<EOF > data.json
 EOF
 
 set -x
-curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
+curl ${OPTIONS} -X POST ${ENDPOINT}${COMMAND} \
 --silent \
 --cookie cookie-jar.txt \
 --cookie-jar cookie-jar.txt \
@@ -808,7 +893,7 @@ for row in $(echo "${people}" | jq -r '.[] | @base64'); do
         echo "------------------------------------------------------------------"
         echo "Delete person"
         
-        COMMAND="/users/${person}"
+        COMMAND="/people/${person}"
         
         rm -rf dump-header.txt output.json status.txt
         
@@ -854,9 +939,57 @@ done
 
 
 echo "------------------------------------------------------------------"
+echo "Refresh tokens"
+
+COMMAND="/refresh"
+
+rm -rf dump-header.txt output.json status.txt
+
+set -x
+curl ${OPTIONS} -X GET ${ENDPOINT}${COMMAND} \
+--silent \
+--cookie cookie-jar.txt \
+--cookie-jar cookie-jar.txt \
+--header "Content-Type: application/json" \
+--header "Accept: application/json" \
+--header "Authorization: Bearer ${AccessToken}" \
+--data-binary "@data.json" \
+--dump-header dump-header.txt \
+--output output.json \
+--write-out %{http_code} > status.txt
+result=$?
+set +x
+
+echo "result: ${result}"
+if [ ! ${result} -eq 0 ]; then
+    echo "Error: $0[${LINENO}]"
+    exit 1
+fi
+
+if [ -f output.json ]; then
+    jq . output.json
+fi
+
+status=$(cat status.txt)
+echo "status: ${status}"
+if [ "${status}" -eq 200 ]; then
+    : # ok
+else
+    echo "Error: $0[${LINENO}]"
+    echo "status: ${status}"
+    exit 1
+fi
+
+
+
+AccessToken=$(jq -r '.accessToken' output.json)
+echo "AccessToken: ${AccessToken}"
+
+
+echo "------------------------------------------------------------------"
 echo "List courts"
 
-COMMAND="/court"
+COMMAND="/courts"
 
 rm -rf dump-header.txt output.json status.txt
 
@@ -903,13 +1036,15 @@ else
     exit 1
 fi
 
+
+
 courts=$(jq .courts output.json)
 for court in $(echo "${courts}" | jq -r '.[]'); do
 
     echo "------------------------------------------------------------------"
     echo "Delete court"
     
-    COMMAND="/court/${court}"
+    COMMAND="/courts/${court}"
     
     rm -rf dump-header.txt output.json status.txt
     
@@ -948,6 +1083,7 @@ for court in $(echo "${courts}" | jq -r '.[]'); do
     fi
 done
 
+echo "------------------------------------------------------------------"
 echo ""
 echo "****************"
 echo "* Success"
